<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JEI8AS0O" ignored="0" name="Test" tests="6" failures="3" timestamp="2020-09-06T15:21:59 EDT" time="95.42" errors="0">
  <testcase name="LoginTestInvalidUser" time="16.31" classname="tests.TestCaseOne">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.TestCaseOne.LoginTestInvalidUser(TestCaseOne.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- LoginTestInvalidUser -->
  <testcase name="LoginTestSuccess" time="3.212" classname="tests.TestCaseOne"/>
  <testcase name="LoginTestInvalidUser" time="16.184" classname="tests.TestCaseTwo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.TestCaseTwo.LoginTestInvalidUser(TestCaseTwo.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- LoginTestInvalidUser -->
  <testcase name="LoginTestSuccess" time="2.674" classname="tests.TestCaseTwo"/>
  <testcase name="LoginTestInvalidUser" time="15.783" classname="tests.TestCaseThree">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.TestCaseThree.LoginTestInvalidUser(TestCaseThree.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- LoginTestInvalidUser -->
  <testcase name="LoginTestSuccess" time="3.143" classname="tests.TestCaseThree"/>
</testsuite> <!-- Test -->
